### PR TITLE
Fix React warning messages

### LINKED ISSUE #99: Unknown prop `object` on <span> tag
I started seeing this error when upgrading Reps

screen shot 2017-02-24 at 7 11 46 pm

### PR DESCRIPTION
**Pull request by nchevobbe**
Fixes #99

Adjust proptypes and fix objectLink uses

### CODE REVIEW

File: src/reps/promise.js [hunk 1]
```diff
@@ -31,12 +31,7 @@ const PromiseRep = React.createClass({
 
   getTitle: function (object) {
     const title = object.class;
-    if (this.props.objectLink) {
-      return this.props.objectLink({
-        object: object
-      }, title);
-    }
-    return title;
+    return this.safeObjectLink({}, title);
```
Comment (jasonLaster) [inline src/reps/promise.js]: this looks like it can be refactored a bit:

perhaps: `safeObjectLink(this.props.objectLink, {}, title)`
or `this.props.safeObjectLink({}, title)`
 
to avoid some duplication

**Comment by jasonLaster** [comment]
It's hard for me to assess given i don't have the context, but it looks sound

**Comment by nchevobbe** [comment]
Thanks for reviewing @jasonLaster & @juliandescottes , I'll fix some of my mistakes today. Maybe it's worth adding a few tests for objectLink too

File: src/reps/array.js [hunk 2]
```diff
@@ -115,6 +114,20 @@ let ArrayRep = React.createClass({
   onClickBracket: function (event) {
   },
 
+  safeObjectLink: function (config, ...children) {
+    if (this.props.objectLink) {
+      return this.props.objectLink(Object.assign({
```
Comment (nchevobbe) [inline src/reps/array.js]: of course we should 😳

File: src/reps/attribute.js [hunk 3]
```diff
@@ -31,19 +31,22 @@ let Attribute = React.createClass({
   render: wrapRender(function () {
     let object = this.props.object;
     let value = object.preview.value;
-    let objectLink = this.props.objectLink || span;
+    let objectLink = (config, ...children) => {
+      if (this.props.objectLink) {
+        return this.props.objectLink(Object.assign({object}, config));
```
Comment (nchevobbe) [inline src/reps/attribute.js]: yup

File: src/reps/grip-array.js [hunk 4]
```diff
@@ -39,14 +39,12 @@ let GripArray = React.createClass({
...
-      return objectLink({
-        object: object
-      }, title, " ");
+    if (this.props.mode === MODE.TINY) {
+      return "";
     }
-    return "";
+
+    let title = `${this.props.title || object.class || "Array"} `;
+    return this.safeObjectLink({}, title);
```
Comment (nchevobbe) [inline src/reps/grip-array.js]: I was wondering if React was adding an extra span node if you do that :thinking: , I'll check

File: src/reps/grip-map.js [hunk 5]
```diff
@@ -157,35 +148,42 @@ const GripMap = React.createClass({
...
-    let objectLink = this.props.objectLink || span;
     if (this.props.mode === MODE.TINY) {
       return (
         span({className: "objectBox objectBox-object"},
-          this.getTitle(object),
-          objectLink({
-            className: "objectLeftBrace",
-            object: object
-          }, "")
+          this.getTitle(object)
```
Comment (nchevobbe) [inline src/reps/grip-map.js]: In tiny mode we only display the title, which is wrapped inside the objectLink. And here, we had the objectLink with an empty content (see `""`), which I guess is pointless. Of course the objectLink could provide his own content ( e.g. `let objectLink = (cfg, children) => DOM.span(cfg, ...["Hello", ...children])` ), but it's not how it is used for now.

File: src/reps/grip-array.js (hunk 4 above)
Comment (juliandescottes) [inline src/reps/grip-array.js]: Ah good point! In this case maybe still concatenate  the blank space with the title in a second step.

File: src/reps/grip-map.js (hunk 5 above)
Comment (juliandescottes) [inline src/reps/grip-map.js]: Ah right! Somehow I thought that objectLeftBrace would add a pseudo el with the left brace as content, but it's not the case at all :)

**Comment by nchevobbe** [comment]
@juliandescottes I fixed the errors you pointed out and added tests for objectLink

**Comment by juliandescottes** [comment]
Thanks for the update and the additional tests Nicolas! Merging.
